### ISSUE TITLE
Extension installed but doesn't show in custom fields 

### ISSUE THREAD

**Issue by robertjawoods** [Zaydme/strapi-plugin-multi-select#1]
Hi there, I've installed your extension following the instructions on the Strapi extension info page. I can see it is installed by looking at: 
![image](https://user-images.githubusercontent.com/19418761/201264503-ce41756c-e44f-40ca-9cda-4badd50e9b66.png) 
and 
![image](https://user-images.githubusercontent.com/19418761/201264559-09c84b89-e5cf-4d6e-b45e-bcdd259abaf9.png)

However, when I go to add the field to a content-type I see this: 
![image](https://user-images.githubusercontent.com/19418761/201264721-8ec1c9e5-db56-4b90-8e2d-d0d2eac86089.png)

Is there something I'm missing? I've restarted Strapi after installing the extension

**Comment by Zaydme** [comment]
@robertjawoods Thank you for the report. However, after creating a new Strapi project, installing the plugin and simply restarting Strapi, I was able to find the plugin under the "Custom" tab
![image](https://user-images.githubusercontent.com/46847212/203183780-d3cef468-79e6-4113-a0bf-87dfa568372f.png)

Can you please confirm if this is still the case

**Comment by robertjawoods** [comment]
Hey, sorry for the late reply. This seems to be resolved now. Thank you.
