### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by M-GRV** [Zaydme/strapi-plugin-multi-select#10]
I have a multi-select with a TON of options.

It would be really nice to be able to type in the available options with a autocomplete of whats available in the list as well as the checkboxes.

Thanks!

**Comment by M-GRV** [comment]
It's fine, Directus has this built-in.

**Comment by Zaydme** [comment]
Fixed with **feat: replace strapi select with react-select** https://github.com/Zaydme/strapi-plugin-multi-select/pull/14

Please update to next release which will be **1.2.0**
