### ISSUE TITLE
Field does not apear

### ISSUE THREAD

**Issue by dimmduh** [Zaydme/strapi-plugin-multi-select#11]
Installed, rebuilded, but nothing. No custom field.
 4.9.2 (node v18.12.0)

**Comment by PenguinOfWar** [comment]
~@Zaydme I am also having this issue on strapi `v4.10.1` after restarting multiple times. Is there a way to manually enable it?~

@dimmduh run `npm run build` in your strapi directory then `npm run develop` again and you will see your custom field. Seems this is now necessary for strapi.

<img width="809" alt="Screenshot 2023-05-16 at 15 45 33" src="https://github.com/Zaydme/strapi-plugin-multi-select/assets/1913241/87b3491e-6a0b-4e06-b63d-5bc676a1069e">

**Comment by codenamezeta** [comment]
Same issue. The plugin marketplace says it's installed but no matter what I try, I never see the custom field available in the custom fields tab. I've tried `npm run build` and `npm run develop` several times with no luck. Please help!

**Comment by Zaydme** [comment]
Please update Strapi to the latest version and make sure you run 

```bash
$ npm install strapi-plugin-multi-select --save
# OR
$ yarn add strapi-plugin-multi-select

$ npm run build
$ npm run develop
```
