### ISSUE TITLE
Preserve selected order

### ISSUE THREAD

**Issue by ajax-fam-d** [Zaydme/strapi-plugin-multi-select#21]
From options list `['a', 'b', 'c']` choose b, then a, selected values list would be `['b', 'a']`

On reload, selected values lose their order, as they're filtered by **possibleOptions** in sanitizedValue and become ['a', 'b']

Would appreciate for this feature, thanks!

**Comment by Zaydme** [comment]
fixed in https://github.com/Zaydme/strapi-plugin-multi-select/commit/47f334ddf8526ae2c5991d3faab2bbe91be6bf45
available in @2.0.1
