### ISSUE TITLE
Add size in Multi Select Input

### ISSUE THREAD

**Issue by Dominic-Preap** [Zaydme/strapi-plugin-multi-select#23]
I would be nice if we can have choose size in multi select tag

![image](https://github.com/Zaydme/strapi-plugin-multi-select/assets/14802170/2764e492-e603-4660-aa92-040edaa4b16c)

**Comment by Zaydme** [comment]
https://github.com/Zaydme/strapi-plugin-multi-select/commit/acc47c3eeeab6c9853e9389a43ae09758fb7787c
