### ISSUE TITLE
Strapi 5

### ISSUE THREAD

**Issue by yevhenskakun** [Zaydme/strapi-plugin-multi-select#30]
Do you plan to support strapi v5?

**Comment by matthewdickinson** [comment]
I put up a draft PR that is working for me. Reviews would be appreciated.

https://github.com/Zaydme/strapi-plugin-multi-select/pull/32

**Comment by anshul-fitsib** [comment]
@Zaydme 

is there any tentative date for the plugin update to support strapi 5?

**Comment by Zaydme** [comment]
[strapi-plugin-multi-select@2.0.0](https://www.npmjs.com/package/strapi-plugin-multi-select/v/2.0.0) with Strapi v5 support has been published, any feedback is appreciated.

Solved with #32
