### ISSUE TITLE
When can we expect Strapi 5 support?

### ISSUE THREAD

**Issue by anshul-fitsib** [Zaydme/strapi-plugin-multi-select#33]
Can you confirm the target date for the plugin update to support Strapi 5?

**Comment by btnalexandre** [comment]
Hello, you can check this issue : https://github.com/Zaydme/strapi-plugin-multi-select/issues/30

**Comment by Zaydme** [comment]
[strapi-plugin-multi-select@2.0.0](https://www.npmjs.com/package/strapi-plugin-multi-select/v/2.0.0) with Strapi v5 support has been published, any feedback is appreciated.

Solved with #32
