### ISSUE TITLE
Does the v2 still support Strapi v4?

### ISSUE THREAD

**Issue by talalong** [Zaydme/strapi-plugin-multi-select#35]
Hi, I tried to upgrade to v2.1.1 from 1.2.3 but I am getting this error:
> ERROR in ./node_modules/strapi-plugin-multi-select/dist/_chunks/index-zVtaChwG.mjs 5573:48-56
export 'useField' (imported as 'useField') was not found in '@strapi/strapi/admin' (possible exports: renderAdmin)

Is this because I am using Strapi v4?

**Comment by Zaydme** [comment]
Yes, Strapi V4 support was dropped on `@2.0.0`
Please use `@1.2.3` or upgrade to Strapi V5, which is always recommended.
The V5 plugin is richer with more features and more to come, and of course ongoing support.
