### ISSUE TITLE
Feature request / suggestion: add option to mark as "private field" in advanced settings

### ISSUE THREAD

**Issue by jkomkin** [Zaydme/strapi-plugin-multi-select#4]
First of all, amazing work! This plugin should be included by default!

Would be great to have an option to hide it from the default API response (This field will not show up in the API response).

**Comment by Zaydme** [comment]
added in https://github.com/Zaydme/strapi-plugin-multi-select/commit/e75f5219f134ef81381383943e8dd842caf027fa

**Comment by jkomkin** [comment]
> added in [e75f521](https://github.com/Zaydme/strapi-plugin-multi-select/commit/e75f5219f134ef81381383943e8dd842caf027fa)

On a Sunday. Legend.
