### ISSUE TITLE
Label does not support other languages

### ISSUE THREAD

**Issue by li9269391** [Zaydme/strapi-plugin-multi-select#8]
```json
[
    "中文:1", // Chinese
    "option 2:2",
    "option 3:3"
]
```

for column 'value' at row 1
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE4\xB8\xAD\xE6\x96\x87...' for column 'value' at row 1

**Comment by Zaydme** [comment]
Fixed in **feat: replace strapi select with react-select** #14
