### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'includes') when adding component with custom plugin

### ISSUE THREAD

**Issue by dmarkbreiter** [Zaydme/strapi-plugin-multi-select#9]
**Strapi version**: 4.6.0
**strapi-plugin-multi-select**: 1.1.0

When adding a component with the custom multi-select plugin field to a dynamic zone, I get a "Whoops! Something went wrong. Please, try again." (see screenshot below). I've also included the console error:

```
TypeError: Cannot read properties of null (reading 'includes')
    at ht (main.ee2267fb.js:12894:988)
    at main.ee2267fb.js:12894:1690
    at Array.map (<anonymous>)
    at be (main.ee2267fb.js:12894:1249)
    at _o (main.ee2267fb.js:9836:54688)
    at l4 (main.ee2267fb.js:9840:9133)
    at Fd (main.ee2267fb.js:9840:989)
    at vc (main.ee2267fb.js:9840:917)
    at Cc (main.ee2267fb.js:9840:768)
    at Ec (main.ee2267fb.js:9838:11068)
qr @ main.ee2267fb.js:9838

```

![Screen Shot 2023-03-10 at 4 11 27 PM](https://user-images.githubusercontent.com/58999191/224456057-920a487c-a491-474b-974f-90734bd7f513.png)

**Comment by arganarazalvaro** [comment]
Did you find a way to solve the problem?

 The same thing happens to me

**Comment by aida-b-f** [comment]
Same here. Happened when upgrading Strapi from v4.5.1 to v4.5.6.

**Comment by dmarkbreiter** [comment]
@arganarazalvaro I couldn't find a solution and had to remove the plug-in entirely and fallback on the built-in select option.

@Zaydme any update on the issue?

**Comment by arganarazalvaro** [comment]
I ended up removing the plugin too, thanks!

**Comment by aida-b-f** [comment]
I've got the plugin working again by upgrading it to 1.1.0

```
 "@strapi/strapi": "4.9.0",
 ....
 "strapi-plugin-multi-select": "^1.1.0"
```

**Comment by dmarkbreiter** [comment]
@aida-b-f, I'm also running v `1.1.0`. @Zaydme does the plugin work on newer version of Strapi?

**Comment by Zaydme** [comment]
Fixed with **feat: replace strapi select with react-select** #14

Please update to next release which will be **1.2.0**

I will not close this issue until someone else confirms it works well with dynamic zones now.

**Comment by Zaydme** [comment]
Migrated to strapi v5, please use @^2.0.0
